{ inputs, ... }:
{
	imports = [
		inputs.equinix.homeModules.equinix
	];

	programs.equinix = {
		enable = true;
		equibop.enable = true;
		discord.enable = false;

		quickCss = "./quickCss.css";
		config = {
			autoUpdate = true;
			autoUpdateNotification = true;
			# eagerPatches = false;
			enabledThemes = [];
			# enabledThemeLinks = [];
			# themeNames = {};
			enableReactDevtools = true;
			frameless = false;
			transparent = false;
			# winCtrlQ = false;
			disableMinSize = false;
			# winNativeTitleBar = false;
			# plugins = {
			# 	ChatInputButtonAPI.enabled = true;
			# 	CommandsAPI.enabled = true;
			# 	DynamicImageModalAPI.enabled = false;
			# 	MemberListDecoratorsAPI.enabled = false;
			# 	MessageAccessoriesAPI.enabled = true;
			# 	MessageDecorationsAPI.enabled = false;
			# 	MessageEventsAPI.enabled = true;
			# 	MessagePopoverAPI.enabled = true;
			# 	MessageUpdaterAPI.enabled = true;
			# 	NicknameIconsAPI.enabled = false;
			# 	ServerListAPI.enabled = false;
			# 	UserSettingsAPI.enabled = true;
			# 	AccountPanelServerProfile = {
			# 		enabled = false;
			# 		prioritizeServerProfile = false;
			# 	};
			# 	AlwaysAnimate.enabled = false;
			# 	AlwaysExpandRoles.enabled = false;
			# 	AlwaysTrust = {
			# 		enabled = true;
			# 		domain = true;
			# 		file = true;
			# 	};
			# 	AnonymiseFileNames = {
			# 		enabled = true;
			# 		anonymiseByDefault = true;
			# 		spoilerMessages = false;
			# 		method = 2;
			# 		randomisedLength = 7;
			# 		consistent = "image";
			# 	};
			# 	AppleMusicRichPresence.enabled = false;
			# 	BANger.enabled = false;
			# 	BetterFolders = {
			# 		enabled = false;
			# 		sidebar = true;
			# 		sidebarAnim = true;
			# 		closeAllFolders = false;
			# 		closeAllHomeButton = false;
			# 		closeOthers = false;
			# 		closeServerFolder = false;
			# 		forceOpen = false;
			# 		keepIcons = false;
			# 		showFolderIcon = 1;
			# 	};
			# 	BetterGifAltText.enabled = true;
			# 	BetterGifPicker.enabled = true;
			# 	BetterNotesBox.enabled = false;
			# 	BetterRoleContext = {
			# 		enabled = true;
			# 		roleIconFileFormat = "png";
			# 	};
			# 	BetterRoleDot.enabled = false;
			# 	BetterSessions.enabled = false;
			# 	BetterSettings = {
			# 		enabled = true;
			# 		disableFade = true;
			# 		organizeMenu = true;
			# 		eagerLoad = true;
			# 	};
			# 	BetterUploadButton.enabled = true;
			# 	BiggerStreamPreview.enabled = false;
			# 	BlurNSFW.enabled = false;
			# 	CallTimer = {
			# 		enabled = true;
			# 		format = "human";
			# 	};
			# 	ClearURLs.enabled = true;
			# 	ClientTheme.enabled = false;
			# 	ColorSighted.enabled = true;
			# 	ConsoleJanitor = {
			# 		enabled = true;
			# 		disableLoggers = false;
			# 		disableSpotifyLogger = true;
			# 		whitelistedLoggers = "GatewaySocket; Routing/Utils";
			# 		allowLevel = {
			# 			error = true;
			# 			warn = false;
			# 			trace = false;
			# 			log = false;
			# 			info = false;
			# 			debug = false;
			# 		};
			# 	};
			# 	ConsoleShortcuts.enabled = false;
			# 	CopyEmojiMarkdown.enabled = false;
			# 	CopyFileContents.enabled = true;
			# 	CopyStickerLinks.enabled = false;
			# 	CopyUserURLs.enabled = true;
			# 	CrashHandler.enabled = true;
			# 	CtrlEnterSend.enabled = false;
			# 	CustomRPC.enabled = false;
			# 	CustomIdle = {
			# 		enabled = true;
			# 		idleTimeout = 0;
			# 		remainInIdle = false;
			# 	};
			# 	Dearrow = {
			# 		enabled = true;
			# 		hideButton = false;
			# 		replaceElements = 0;
			# 		dearrowByDefault = true;
			# 	};
			# 	Decor.enabled = false;
			# 	DisableCallIdle.enabled = true;
			# 	DontRoundMyTimestamps.enabled = true;
			# 	Experiments.enabled = false;
			# 	F8Break.enabled = false;
			# 	FakeNitro = {
			# 		enabled = true;
			# 		enableEmojiBypass = false;
			# 		emojiSize = 48;
			# 		transformEmojis = true;
			# 		enableStickerBypass = false;
			# 		stickerSize = 160;
			# 		transformStickers = true;
			# 		transformCompoundSentence = false;
			# 		enableStreamQualityBypass = true;
			# 		useStickerHyperLinks = true;
			# 		useEmojiHyperLinks = true;
			# 		hyperLinkText = "{{NAME}}";
			# 		disableEmbedPermissionCheck = false;
			# 	};
			# 	FakeProfileThemes.enabled = false;
			# 	FavoriteEmojiFirst.enabled = true;
			# 	FavoriteGifSearch.enabled = true;
			# 	FixCodeblockGap.enabled = true;
			# 	FixImagesQuality.enabled = true;
			# 	FixSpotifyEmbeds.enabled = false;
			# 	FixYoutubeEmbeds.enabled = false;
			# 	ForceOwnerCrown.enabled = true;
			# 	FriendInvites.enabled = false;
			# 	FriendsSince.enabled = false;
			# 	FullSearchContext.enabled = false;
			# 	FullUserInChatbox.enabled = true;
			# 	GameActivityToggle.enabled = false;
			# 	GifPaste.enabled = false;
			# 	GreetStickerPicker.enabled = false;
			# 	HideMedia.enabled = false;
			# 	ILoveSpam.enabled = true;
			# 	IgnoreActivities.enabled = false;
			# 	ImageLink.enabled = false;
			# 	ImageZoom.enabled = false;
			# 	ImplicitRelationships.enabled = false;
			# 	InvisibleChat.enabled = false;
			# 	IrcColors.enabled = false;
			# 	KeepCurrentChannel.enabled = true;
			# 	LastFMRichPresence.enabled = false;
			# 	LoadingQuotes = {
			# 		enabled = false;
			# 		replaceEvents = true;
			# 		enablePluginPresetQuotes = true;
			# 		enableDiscordPresetQuotes = false;
			# 		additionalQuotes = "";
			# 		additionalQuotesDelimiter = "|";
			# 	};
			# 	MemberCount.enabled = false;
			# 	MentionAvatars = {
			# 		enabled = true;
			# 		showAtSymbol = true;
			# 	};
			# 	MessageClickActions = {
			# 		enabled = true;
			# 		enableDeleteOnClick = true;
			# 		enableDoubleClickToEdit = true;
			# 		enableDoubleClickToReply = true;
			# 		requireModifier = false;
			# 	};
			# 	MessageLatency.enabled = false;
			# 	MessageLinkEmbeds = {
			# 		enabled = true;
			# 		automodEmbeds = "never";
			# 		listMode = "blacklist";
			# 		idList = "";
			# 	};
			# 	MessageLogger = {
			# 		enabled = true;
			# 		deleteStyle = "text";
			# 		logDeletes = true;
			# 		collapseDeleted = false;
			# 		logEdits = true;
			# 		inlineEdits = true;
			# 		ignoreBots = false;
			# 		ignoreSelf = false;
			# 		ignoreUsers = "";
			# 		ignoreChannels = "";
			# 		ignoreGuilds = "";
			# 		showEditDiffs = false;
			# 	};
			# 	MessageTags.enabled = false;
			# 	MoreCommands.enabled = false;
			# 	MoreKaomoji.enabled = false;
			# 	Moyai.enabled = false;
			# 	MutualGroupDMs.enabled = false;
			# 	NewGuildSettings.enabled = false;
			# 	NoBlockedMessages.enabled = false;
			# 	NoDevtoolsWarning.enabled = true;
			# 	NoF1.enabled = false;
			# 	NoMaskedUrlPaste.enabled = false;
			# 	NoMosaic.enabled = false;
			# 	NoOnboardingDelay.enabled = true;
			# 	NoPendingCount.enabled = false;
			# 	NoProfileThemes.enabled = false;
			# 	NoRPC.enabled = false;
			# 	NoReplyMention.enabled = false;
			# 	NoServerEmojis.enabled = false;
			# 	NoSystemBadge.enabled = false;
			# 	NoTypingAnimation.enabled = true;
			# 	NoUnblockToJump.enabled = true;
			# 	NormalizeMessageLinks.enabled = false;
			# 	NotificationVolume.enabled = false;
			# 	NSFWGateBypass.enabled = false;
			# 	OnePingPerDM.enabled = false;
			# 	Oneko.enabled = false;
			# 	OpenInApp = {
			# 		enabled = true;
			# 		spotify = true;
			# 		steam = true;
			# 		epic = true;
			# 		tidal = true;
			# 		itunes = true;
			# 	};
			# 	OverrideForumDefaults.enabled = false;
			# 	PartyMode.enabled = false;
			# 	PauseInvitesForever.enabled = true;
			# 	PermissionFreeWill = {
			# 		enabled = false;
			# 		lockout = true;
			# 		onboarding = true;
			# 	};
			# 	PermissionsViewer.enabled = false;
			# 	petpet.enabled = false;
			# 	PictureInPicture.enabled = false;
			# 	PinDMs.enabled = false;
			# 	PlainFolderIcon.enabled = false;
			# 	PlatformIndicators.enabled = false;
			# 	PreviewMessage.enabled = true;
			# 	QuickMention.enabled = false;
			# 	QuickReply.enabled = false;
			# 	ReactErrorDecoder.enabled = true;
			# 	ReadAllNotificationsButton.enabled = false;
			# 	RelationshipNotifier = {
			# 		enabled = true;
			# 		notices = false;
			# 		offlineRemovals = true;
			# 		friends = true;
			# 		friendRequestCancels = true;
			# 		servers = true;
			# 		groups = true;
			# 	};
			# 	ReplaceGoogleSearch.enabled = false;
			# 	ReplyTimestamp.enabled = false;
			# 	RevealAllSpoilers.enabled = false;
			# 	ReverseImageSearch.enabled = false;
			# 	ReviewDB.enabled = false;
			# 	RoleColorEverywhere.enabled = false;
			# 	SecretRingToneEnabler.enabled = false;
			# 	Summaries.enabled = false;
			# 	SendTimestamps = {
			# 		enabled = true;
			# 		replaceMessageContents = true;
			# 	};
			# 	ServerInfo.enabled = false;
			# 	ServerListIndicators.enabled = false;
			# 	ShikiCodeblocks.enabled = false;
			# 	ShowAllMessageButtons.enabled = false;
			# 	ShowConnections.enabled = false;
			# 	ShowHiddenChannels = {
			# 		enabled = true;
			# 		channelStyle = 0;
			# 		showMode = 0;
			# 		defaultAllowedUsersAndRolesDropdownState = true;
			# 	};
			# 	ShowHiddenThings = {
			# 		enabled = true;
			# 		showTimeouts = true;
			# 		showInvitesPaused = true;
			# 		showModView = true;
			# 	};
			# 	ShowMeYourName.enabled = false;
			# 	ShowTimeoutDuration = {
			# 		enabled = true;
			# 		displayStyle = "ssalggnikool";
			# 	};
			# 	SilentMessageToggle.enabled = false;
			# 	SilentTyping = {
			# 		enabled = true;
			# 		enabledGlobally = true;
			# 		hideChatBoxTypingIndicators = false;
			# 		hideMembersListTypingIndicators = false;
			# 		chatIcon = true;
			# 		chatIconLeftClickAction = "channel";
			# 		chatIconMiddleClickAction = "settings";
			# 		chatIconRightClickAction = "global";
			# 		chatContextMenu = true;
			# 		defaultHidden = true;
			# 		enabledLocations = "";
			# 		disabledLocations = "";
			# 	};
			# 	SortFriendRequests = {
			# 		enabled = true;
			# 		showDates = false;
			# 	};
			# 	SpotifyControls.enabled = false;
			# 	SpotifyCrack = {
			# 		enabled = true;
			# 		noSpotifyAutoPause = true;
			# 		keepSpotifyActivityOnIdle = false;
			# 	};
			# 	SpotifyShareCommands.enabled = true;
			# 	StartupTimings.enabled = true;
			# 	StickerPaste.enabled = false;
			# 	StreamerModeOn.enabled = false;
			# 	SuperReactionTweaks.enabled = false;
			# 	TextReplace.enabled = false;
			# 	ThemeAttributes.enabled = false;
			# 	Translate.enabled = false;
			# 	TypingIndicator = {
			# 		enabled = true;
			# 		includeCurrentChannel = true;
			# 		includeMutedChannels = false;
			# 		includeBlockedUsers = false;
			# 		indicatorMode = 3;
			# 	};
			# 	TypingTweaks.enabled = false;
			# 	Unindent.enabled = true;
			# 	UnlockedAvatarZoom.enabled = false;
			# 	UnsuppressEmbeds.enabled = false;
			# 	UserMessagesPronouns = {
			# 		enabled = true;
			# 		pronounsFormat = "LOWERCASE";
			# 		showSelf = true;
			# 	};
			# 	UserVoiceShow.enabled = false;
			# 	USRBG.enabled = false;
			# 	ValidReply.enabled = true;
			# 	ValidUser.enabled = true;
			# 	VoiceChatDoubleClick.enabled = true;
			# 	VcNarrator.enabled = false;
			# 	ViewIcons.enabled = false;
			# 	ViewRaw.enabled = false;
			# 	VoiceDownload.enabled = true;
			# 	VoiceMessages = {
			# 		enabled = true;
			# 		noiseSuppression = true;
			# 		echoCancellation = true;
			# 	};
			# 	VolumeBooster = {
			# 		enabled = true;
			# 		multiplier = 3;
			# 	};
			# 	WhoReacted.enabled = false;
			# 	XSOverlay.enabled = false;
			# 	YoutubeAdblock.enabled = false;
			# 	AllCallTimers = {
			# 		enabled = true;
			# 		showWithoutHover = true;
			# 		showRoleColor = true;
			# 		trackSelf = true;
			# 		showSeconds = true;
			# 		format = "human";
			# 		watchLargeGuilds = false;
			# 	};
			# 	AltKrispSwitch.enabled = false;
			# 	AlwaysExpandProfile.enabled = false;
			# 	AmITyping.enabled = true;
			# 	Anammox.enabled = false;
			# 	AtSomeone.enabled = false;
			# 	BannersEverywhere.enabled = false;
			# 	DecodeBase64 = {
			# 		enabled = false;
			# 		clickMethod = "Left";
			# 	};
			# 	BetterActivities = {
			# 		enabled = true;
			# 		removeGameActivityStatus = false;
			# 		memberList = true;
			# 		userPopout = true;
			# 		hideTooltip = true;
			# 		renderGifs = true;
			# 		iconSize = 15;
			# 	};
			# 	BetterAudioPlayer.enabled = false;
			# 	BetterBanReasons = {
			# 		enabled = true;
			# 		reasons = [
			# 			""
			# 		];
			# 		isTextInputDefault = true;
			# 	};
			# 	BetterBlockedUsers.enabled = false;
			# 	BetterInvites.enabled = true;
			# 	BetterQuickReact = {
			# 		enabled = true;
			# 		frequentEmojis = true;
			# 		rows = 1;
			# 		columns = 6;
			# 		compactMode = true;
			# 		scroll = true;
			# 	};
			# 	BetterPlusReacts.enabled = true;
			# 	BlockKeywords.enabled = false;
			# 	BlockKrisp.enabled = false;
			# 	BypassStatus.enabled = false;
			# 	ChannelBadges = {
			# 		enabled = true;
			# 		oneBadgePerChannel = false;
			# 		showTextBadge = true;
			# 		showVoiceBadge = true;
			# 		showCategoryBadge = true;
			# 		showDirectoryBadge = true;
			# 		showAnnouncementThreadBadge = true;
			# 		showPublicThreadBadge = true;
			# 		showPrivateThreadBadge = true;
			# 		showStageBadge = true;
			# 		showAnnouncementBadge = true;
			# 		showForumBadge = true;
			# 		showMediaBadge = true;
			# 		showNSFWBadge = true;
			# 		showLockedBadge = true;
			# 		showRulesBadge = true;
			# 		showUnknownBadge = true;
			# 		textBadgeLabel = "Text";
			# 		voiceBadgeLabel = "Voice";
			# 		categoryBadgeLabel = "Category";
			# 		announcementBadgeLabel = "News";
			# 		announcementThreadBadgeLabel = "News Thread";
			# 		publicThreadBadgeLabel = "Thread";
			# 		privateThreadBadgeLabel = "Private Thread";
			# 		stageBadgeLabel = "Stage";
			# 		directoryBadgeLabel = "Directory";
			# 		forumBadgeLabel = "Forum";
			# 		mediaBadgeLabel = "Media";
			# 		nsfwBadgeLabel = "NSFW";
			# 		lockedBadgeLabel = "Locked";
			# 		rulesBadgeLabel = "Rules";
			# 		unknownBadgeLabel = "Unknown";
			# 	};
			# 	ChannelTabs.enabled = false;
			# 	CharacterCounter = {
			# 		enabled = true;
			# 		colorEffects = true;
			# 	};
			# 	CleanChannelName.enabled = true;
			# 	ClientSideBlock = {
			# 		enabled = true;
			# 		usersToBlock = "";
			# 		hideBlockedUsers = true;
			# 		hideBlockedMessages = true;
			# 		hideEmptyRoles = true;
			# 		blockedReplyDisplay = "displayText";
			# 		guildBlackList = "";
			# 		guildWhiteList = "";
			# 	};
			# 	ClipsEnhancements.enabled = false;
			# 	CommandPalette.enabled = false;
			# 	CopyProfileColors.enabled = false;
			# 	CopyUserMention.enabled = false;
			# 	CustomSounds.enabled = false;
			# 	CustomTimestamps.enabled = false;
			# 	CustomUserColors.enabled = false;
			# 	CuteAnimeBoys.enabled = false;
			# 	CuteNekos.enabled = false;
			# 	CutePats.enabled = false;
			# 	Demonstration.enabled = false;
			# 	DisableAnimations.enabled = false;
			# 	DisableCameras.enabled = false;
			# 	DontFilterMe.enabled = false;
			# 	Encryptcord.enabled = false;
			# 	EquicordToolbox.enabled = false;
			# 	Equissant.enabled = false;
			# 	ExportContacts.enabled = false;
			# 	FakeProfileThemesAndEffects = {
			# 		enabled = false;
			# 		prioritizeNitro = false;
			# 		hideBuilder = false;
			# 	};
			# 	FindReply.enabled = false;
			# 	FixFileExtensions.enabled = true;
			# 	FollowVoiceUser.enabled = false;
			# 	FontLoader.enabled = false;
			# 	ForwardAnywhere.enabled = false;
			# 	Freaky = {
			# 		enabled = false;
			# 		addFreakyEnding = true;
			# 	};
			# 	FrequentQuickSwitcher.enabled = false;
			# 	FriendCodes.enabled = false;
			# 	FriendTags.enabled = false;
			# 	FriendshipRanks.enabled = false;
			# 	FullVCPFP.enabled = false;
			# 	GensokyoRadioRPC.enabled = false;
			# 	GifCollections.enabled = false;
			# 	GifRoulette = {
			# 		enabled = false;
			# 		pingOwnerChance = true;
			# 	};
			# 	GitHubRepos.enabled = false;
			# 	Glide.enabled = false;
			# 	GlobalBadges = {
			# 		enabled = true;
			# 		showPrefix = true;
			# 		showCustom = true;
			# 	};
			# 	GoogleThat = {
			# 		enabled = true;
			# 		hyperlink = false;
			# 		defaultEngine = "Google";
			# 	};
			# 	HideChatButtons = {
			# 		enabled = false;
			# 		Color = false;
			# 		Open = false;
			# 	};
			# 	HideServers.enabled = false;
			# 	HolyNotes.enabled = false;
			# 	HomeTyping.enabled = true;
			# 	HopOn = {
			# 		enabled = false;
			# 		regex = "hop on (?:fortnite|fn)";
			# 		url = "com.epicgames.launcher://apps/fn%3A4fe75bbc5a674f4f9b356b5c90567da5%3AFortnite?action=launch&silent=true";
			# 	};
			# 	Husk.enabled = false;
			# 	IRememberYou.enabled = false;
			# 	IconViewer.enabled = false;
			# 	Identity.enabled = false;
			# 	IgnoreCalls.enabled = false;
			# 	IgnoreTerms.enabled = true;
			# 	ImagePreview.enabled = false;
			# 	ImgToGif.enabled = true;
			# 	InRole.enabled = false;
			# 	InstantScreenshare.enabled = false;
			# 	JumpToStart.enabled = false;
			# 	Jumpscare.enabled = false;
			# 	KeyboardSounds.enabled = false;
			# 	KeywordNotify.enabled = false;
			# 	LastActive.enabled = false;
			# 	LimitMiddleClickPaste.enabled = false;
			# 	LoginWithQR.enabled = true;
			# 	MediaDownloader.enabled = false;
			# 	MediaPlaybackSpeed = {
			# 		enabled = false;
			# 		defaultVoiceMessageSpeed = 1;
			# 		defaultVideoSpeed = 1;
			# 		defaultAudioSpeed = 1;
			# 	};
			# 	Meow.enabled = false;
			# 	MessageBurst.enabled = false;
			# 	MessageColors = {
			# 		enabled = true;
			# 		renderType = 1;
			# 		enableShortHexCodes = true;
			# 		blockView = 1;
			# 	};
			# 	MessageLinkTooltip.enabled = false;
			# 	MessageLoggerEnhanced.enabled = false;
			# 	MessageTranslate.enabled = false;
			# 	ModalFade.enabled = false;
			# 	MoreStickers.enabled = false;
			# 	MoreUserTags.enabled = false;
			# 	Morse.enabled = false;
			# 	NeverPausePreviews.enabled = true;
			# 	NewPluginsManager.enabled = true;
			# 	NoAppsAllowed.enabled = false;
			# 	NoBulletPoints.enabled = true;
			# 	NoDeleteSafety.enabled = false;
			# 	NoMirroredCamera.enabled = false;
			# 	NoModalAnimation.enabled = true;
			# 	NoNitroUpsell.enabled = true;
			# 	NoOnboarding.enabled = false;
			# 	NoRoleHeaders.enabled = false;
			# 	NotificationTitle.enabled = false;
			# 	PinIcon.enabled = true;
			# 	PingNotifications.enabled = false;
			# 	PlatformSpoofer = {
			# 		enabled = false;
			# 		platform = "desktop";
			# 	};
			# 	PolishWording = {
			# 		enabled = true;
			# 		quickDisable = false;
			# 		blockedWords = "";
			# 		fixApostrophes = true;
			# 		expandContractions = false;
			# 		fixCapitalization = false;
			# 		fixPunctuation = false;
			# 		fixPunctuationFrequency = 100;
			# 	};
			# 	PurgeMessages.enabled = false;
			# 	QuestCompleter.enabled = false;
			# 	QuestionMarkReplacement = {
			# 		enabled = false;
			# 		replace = ":face_with_monocle:";
			# 	};
			# 	Quoter.enabled = false;
			# 	RandomVoice.enabled = false;
			# 	Remix = {
			# 		enabled = true;
			# 		remixTag = true;
			# 	};
			# 	RemixMe.enabled = false;
			# 	RepeatMessage.enabled = false;
			# 	ReplyPingControl.enabled = false;
			# 	RPCEditor.enabled = false;
			# 	RPCStats.enabled = false;
			# 	SearchFix.enabled = true;
			# 	SekaiStickers.enabled = false;
			# 	ServerSearch.enabled = false;
			# 	ShowBadgesInChat.enabled = false;
			# 	SidebarChat.enabled = false;
			# 	Signature.enabled = false;
			# 	Slap.enabled = false;
			# 	SoundBoardLogger.enabled = false;
			# 	SplitLargeMessages = {
			# 		enabled = false;
			# 		maxLength = 0;
			# 		disableFileConversion = true;
			# 		sendDelay = 1;
			# 		hardSplit = false;
			# 		slowmodeMax = 5;
			# 	};
			# 	SpotifyLyrics.enabled = false;
			# 	StatsfmPresence.enabled = false;
			# 	StatusPresets.enabled = false;
			# 	StatusWhilePlaying.enabled = false;
			# 	SteamStatusSync.enabled = false;
			# 	StickerBlocker.enabled = false;
			# 	TalkInReverse.enabled = false;
			# 	TeX.enabled = true;
			# 	TextToSpeech.enabled = false;
			# 	ThemeLibrary.enabled = false;
			# 	Timezones = {
			# 		enabled = true;
			# 		"Show Own Timezone" = true;
			# 		"24h Time" = true;
			# 		showMessageHeaderTime = false;
			# 		showProfileTime = true;
			# 		useDatabase = true;
			# 		preferDatabaseOverLocal = true;
			# 		databaseUrl = "https://timezone.creations.works";
			# 		askedTimezone = true;
			# 	};
			# 	Title.enabled = false;
			# 	ToastNotifications.enabled = false;
			# 	TosuRPC.enabled = false;
			# 	"Translate+" = {
			# 		enabled = false;
			# 	};
			# 	UnitConverter.enabled = false;
			# 	UnlimitedAccounts = {
			# 		enabled = true;
			# 		maxAccounts = 0;
			# 	};
			# 	UnreadCountBadge.enabled = false;
			# 	UserPFP.enabled = false;
			# 	UwUifier.enabled = false;
			# 	VcNarratorCustom.enabled = false;
			# 	VCPanelSettings.enabled = false;
			# 	VCSupport.enabled = true;
			# 	VencordRPC.enabled = false;
			# 	VideoSpeed.enabled = false;
			# 	ViewRawVariant.enabled = false;
			# 	VoiceChatUtilities.enabled = false;
			# 	VoiceJoinMessages.enabled = false;
			# 	WebpackTarball.enabled = false;
			# 	WhitelistedEmojis.enabled = false;
			# 	WhosWatching.enabled = false;
			# 	WigglyText.enabled = false;
			# 	Woof.enabled = false;
			# 	WriteUpperCase.enabled = false;
			# 	YoutubeDescription.enabled = false;
			# 	Settings = {
			# 		enabled = true;
			# 		settingsLocation = "aboveNitro";
			# 	};
			# 	AlwaysExpandProfiles.enabled = true;
			# 	Animalese.enabled = false;
			# 	AudioBookShelfRichPresence.enabled = false;
			# 	AutoJump = {
			# 		enabled = true;
			# 		autoJumping = false;
			# 	};
			# 	BetterCommands = {
			# 		enabled = false;
			# 		autoFillArguments = true;
			# 	};
			# 	DisableDeepLinks.enabled = true;
			# 	EquicordHelper.enabled = true;
			# 	NoTrack = {
			# 		enabled = true;
			# 		disableAnalytics = true;
			# 	};
			# 	SupportHelper.enabled = true;
			# 	WebContextMenus = {
			# 		enabled = true;
			# 		addBack = false;
			# 	};
			# 	BypassPinPrompt.enabled = false;
			# 	DiscordDevBanner.enabled = false;
			# 	FastDeleteChannels.enabled = false;
			# 	MessageFetchTimer.enabled = false;
			# 	SelfForward.enabled = true;
			# 	ShowResourceChannels.enabled = true;
			# 	ExpressionCloner.enabled = true;
			# 	GuildPickerDumper.enabled = false;
			# 	ToggleVideoBind.enabled = false;
			# 	WebRichPresence = {
			# 		enabled = false;
			# 	};
			# 	ImageFilename.enabled = false;
			# 	WebKeybinds.enabled = true;
			# 	WebScreenShareFixes.enabled = true;
			# 	ContentWarning.enabled = false;
			# 	CopyStatusUrls.enabled = false;
			# 	CustomFolderIcons.enabled = false;
			# 	Downloadify.enabled = false;
			# 	ExportMessages = {
			# 		enabled = true;
			# 		openFileAfterExport = true;
			# 	};
			# 	FriendCloud.enabled = false;
			# 	GuildTagSettings = {
			# 		enabled = true;
			# 		hideTags = false;
			# 		disableAdoptTagPrompt = true;
			# 	};
			# 	Ingtoninator.enabled = false;
			# 	InviteDefaults = {
			# 		enabled = true;
			# 		inviteDuration = 0;
			# 		maxUses = 0;
			# 		temporaryMembership = false;
			# 	};
			# 	JellyfinRichPresence.enabled = false;
			# 	MusicControls = {
			# 		enabled = true;
			# 		hoverControls = false;
			# 		ShowMusicNoteOnNoLyrics = true;
			# 		LyricsPosition = "below";
			# 		LyricsProvider = "Spotify";
			# 		TranslateTo = "en";
			# 		LyricsConversion = "None";
			# 		FallbackProvider = true;
			# 		ShowFailedToasts = true;
			# 		LyricDelay = 0;
			# 		showSpotifyControls = true;
			# 		showSpotifyLyrics = false;
			# 		useSpotifyUris = true;
			# 		previousButtonRestartsTrack = true;
			# 		showTidalControls = false;
			# 		showTidalLyrics = false;
			# 		TidalLyricFetch = "https://api.vmohammad.dev/";
			# 		TidalSyncMode = "line";
			# 	};
			# 	OrbolayBridge.enabled = false;
			# 	QuestFocused.enabled = false;
			# 	Questify.enabled = false;
			# 	SaveFavoriteGIFs.enabled = false;
			# 	Soggy.enabled = false;
			# 	SpotifyActivityToggle.enabled = false;
			# 	StreamingCodecDisabler.enabled = false;
			# 	TidalEmbeds.enabled = false;
			# 	TiktokTTS.enabled = false;
			# 	WallpaperFree.enabled = false;
			# 	BadgeAPI.enabled = true;
			# };
		};
	};
}
