[window]
startup_mode = "Maximized"

[env]
opacity = "0.5"

[font.normal]
family = "ComicShannsMono Nerd Font Mono"

[cursor]
[cursor.style]
shape = "Beam"
blinking = "Off"

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "/run/current-system/sw/bin/nu"
